export const QUOTES = [
  { text: "what you think, you become.", author: "buddha" },
  { text: "the only way to do great work is to love what you do.", author: "steve jobs" },
  { text: "discipline is the bridge between goals and accomplishment.", author: "jim rohn" },
  { text: "we are what we repeatedly do. excellence, then, is not an act, but a habit.", author: "aristotle" },
  { text: "don't count the days, make the days count.", author: "muhammad ali" },
  { text: "the secret of getting ahead is getting started.", author: "mark twain" },
  { text: "it always seems impossible until it's done.", author: "nelson mandela" },
  { text: "well begun is half done.", author: "aristotle" },
  { text: "your time is limited, don't waste it living someone else's life.", author: "steve jobs" },
  { text: "the best way to predict the future is to create it.", author: "peter drucker" },
  { text: "success is not final, failure is not fatal: it is the courage to continue that counts.", author: "winston churchill" },
  { text: "believe you can and you're halfway there.", author: "theodore roosevelt" },
  { text: "everything you've ever wanted is on the other side of fear.", author: "george addair" },
  { text: "do what you can, with what you have, where you are.", author: "theodore roosevelt" },
  { text: "the only limit to our realization of tomorrow will be our doubts of today.", author: "franklin d. roosevelt" },
  { text: "act as if what you do makes a difference. it does.", author: "william james" },
  { text: "quality is not an act, it is a habit.", author: "aristotle" },
  { text: "the journey of a thousand miles begins with one step.", author: "lao tzu" },
  { text: "strive not to be a success, but rather to be of value.", author: "albert einstein" },
  { text: "the mind is everything. what you think you become.", author: "buddha" },
  { text: "you miss 100% of the shots you don't take.", author: "wayne gretzky" },
  { text: "whether you think you can or you think you can't, you're right.", author: "henry ford" },
  { text: "i have not failed. i've just found 10,000 ways that won't work.", author: "thomas edison" },
  { text: "it is never too late to be what you might have been.", author: "george eliot" },
  { text: "life is what happens when you're busy making other plans.", author: "john lennon" },
  { text: "a person who never made a mistake never tried anything new.", author: "albert einstein" },
  { text: "the only person you are destined to become is the person you decide to be.", author: "ralph waldo emerson" },
  { text: "everything has beauty, but not everyone sees it.", author: "confucius" },
  { text: "simplicity is the ultimate sophistication.", author: "leonardo da vinci" },
  { text: "it does not matter how slowly you go as long as you do not stop.", author: "confucius" },
  { text: "our life is frittered away by detail. simplify, simplify.", author: "henry david thoreau" },
  { text: "be the change that you wish to see in the world.", author: "mahatma gandhi" },
  { text: "happiness depends upon ourselves.", author: "aristotle" },
  { text: "change your thoughts and you change your world.", author: "norman vincent peale" },
  { text: "the more i read, the more i acquire, the more certain i am that i know nothing.", author: "voltaire" },
  { text: "time is a created thing. to say 'i don't have time' is to say 'i don't want to'.", author: "lao tzu" },
  { text: "yesterday i was clever, so i wanted to change the world. today i am wise, so i am changing myself.", author: "rumi" },
  { text: "the unexamined life is not worth living.", author: "socrates" },
  { text: "he who has a why to live can bear almost any how.", author: "friedrich nietzsche" },
  { text: "you are the master of your destiny. you can influence, direct and control your own environment.", author: "napoleon hill" },
  { text: "don't let yesterday take up too much of today.", author: "will rogers" },
  { text: "the only true wisdom is in knowing you know nothing.", author: "socrates" },
  { text: "life is 10% what happens to us and 90% how we react to it.", author: "charles r. swindoll" },
  { text: "if you want to lift yourself up, lift up someone else.", author: "booker t. washington" },
  { text: "limitations live only in our minds.", author: "jamie paolinetti" },
  { text: "the best revenge is massive success.", author: "frank sinatra" },
  { text: "an unexamined life is not worth living.", author: "socrates" },
  { text: "nothing is impossible, the word itself says 'i'm possible!'", author: "audrey hepburn" },
  { text: "i would rather die on my feet than live on my knees.", author: "emiliano zapata" },
  { text: "he who is not courageous enough to take risks will accomplish nothing in life.", author: "muhammad ali" },
  { text: "your life does not get better by chance, it gets better by change.", author: "jim rohn" },
  { text: "motivation is what gets you started. habit is what keeps you going.", author: "jim ryun" },
  { text: "be not afraid of greatness. some are born great, some achieve greatness, and others have greatness thrust upon them.", author: "william shakespeare" },
  { text: "the harder i work, the luckier i get.", author: "samuel goldwyn" },
  { text: "don't wait. the time will never be just right.", author: "napoleon hill" },
  { text: "do one thing every day that scares you.", author: "eleanor roosevelt" },
  { text: "it's not whether you get knocked down, it's whether you get up.", author: "vince lombardi" },
  { text: "if you're going through hell, keep going.", author: "winston churchill" },
  { text: "a goal is a dream with a deadline.", author: "napoleon hill" },
  { text: "dream big and dare to fail.", author: "norman vaughan" },
  { text: "perseverance is not a long race; it is many short races one after the other.", author: "walter elliot" },
  { text: "you must be the change you wish to see in the world.", author: "mahatma gandhi" },
  { text: "hardships often prepare ordinary people for an extraordinary destiny.", author: "c.s. lewis" },
  { text: "the only way to find the limits of the possible is by going beyond them into the impossible.", author: "arthur c. clarke" },
  { text: "it is our choices that show what we truly are, far more than our abilities.", author: "j.k. rowling" },
  { text: "don't be pushed around by the fears in your mind. be led by the dreams in your heart.", author: "roy t. bennett" },
  { text: "it's not the years in your life that count. it's the life in your years.", author: "abraham lincoln" },
  { text: "the greatest glory in living lies not in never falling, but in rising every time we fall.", author: "nelson mandela" },
  { text: "the road to success and the road to failure are almost exactly the same.", author: "colin r. davis" },
  { text: "knowledge is power.", author: "francis bacon" },
  { text: "the way to get started is to quit talking and begin doing.", author: "walt disney" },
  { text: "if you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", author: "james cameron" },
  { text: "if you look at what you have in life, you'll always have more.", author: "oprah winfrey" },
  { text: "if you can dream it, you can do it.", author: "walt disney" },
  { text: "may you live every day of your life.", author: "jonathan swift" },
  { text: "life is either a daring adventure or nothing at all.", author: "helen keller" },
  { text: "turn your wounds into wisdom.", author: "oprah winfrey" },
  { text: "get busy living or get busy dying.", author: "stephen king" },
  { text: "you only live once, but if you do it right, once is enough.", author: "mae west" },
  { text: "many of life's failures are people who did not realize how close they were to success when they gave up.", author: "thomas edison" },
  { text: "if you want to live a happy life, tie it to a goal, not to people or things.", author: "albert einstein" },
  { text: "never let the fear of striking out keep you from playing the game.", author: "babe ruth" },
  { text: "money and success don't change people; they merely amplify what is already there.", author: "will smith" },
  { text: "the whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "henry ford" },
  { text: "not how long, but how well you have lived is the main thing.", author: "seneca" },
  { text: "if life were predictable it would cease to be life, and be without flavor.", author: "eleanor roosevelt" },
  { text: "life is not a problem to be solved, but a reality to be experienced.", author: "soren kierkegaard" },
  { text: "the unexamined life is not worth living.", author: "socrates" },
  { text: "your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "steve jobs" },
  { text: "keep smiling, because life is a beautiful thing and there's so much to smile about.", author: "marilyn monroe" },
  { text: "the power of imagination makes us infinite.", author: "john muir" },
  { text: "the best way to find yourself is to lose yourself in the service of others.", author: "mahatma gandhi" },
  { text: "the future belongs to those who believe in the beauty of their dreams.", author: "eleanor roosevelt" },
  { text: "nothing great was ever achieved without enthusiasm.", author: "ralph waldo emerson" },
  { text: "the more that you read, the more things you will know. the more that you learn, the more places you'll go.", author: "dr. seuss" },
  { text: "keep your face always toward the sunshine—and shadows will fall behind you.", author: "walt whitman" },
  { text: "be yourself; everyone else is already taken.", author: "oscar wilde" },
  { text: "you cannot shake hands with a clenched fist.", author: "indira gandhi" },
  { text: "let us make our future now, and let us make our dreams tomorrow's reality.", author: "malala yousafzai" },
  { text: "the only thing we have to fear is fear itself.", author: "franklin d. roosevelt" },
  { text: "don't let the noise of others' opinions drown out your own inner voice.", author: "steve jobs" },
  { text: "where there is love there is life.", author: "mahatma gandhi" }
];