// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xywbivdtaurgtzbinnss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5d2JpdmR0YXVyZ3R6YmlubnNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NjA3MzQsImV4cCI6MjA4NzQzNjczNH0.fziZ2CMouROZq2TvORJ_iNiikzKhM6Fe_3F3tsnbiGk";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);